### ISSUE TITLE
MPRA model lines 77-80 and 360-371

### ISSUE THREAD

**Issue by amysorekar** [tewhey-lab/MPRAmodel#2]
## Lines: 
```
else{
  attributesData$ctrl_exp <- projectName
  attributesData[grep(negCtrlName, attributesData$project),]$ctrl_exp <- negCtrlName
  attributesData[grep(posCtrlName, attributesData$project),]$ctrl_exp <- posCtrlName
}
```
## Inputs: 
*Counts table:* ENCFF130WRM.tsv
*Attributes table:* OL45.attributes
*Condition Table:* the one from this github with an added plasmid_r5 and DNA

## Error: 

`Error in $<-.data.frame(*tmp*, "ctrl_exp", value = "negCtrl") : 
  replacement has 1 row, data has 0`

--- 
If I comment that block out, the code runs until line 360:

```
 message("Plotting Normalization Curves")
 pdf(paste0("plots/",file_prefix,"_",fileDate(),"_Normalized_FC_Density_",celltype,".pdf"),wid
 plot(density(temp_outputB[attribute_ids,"log2FoldChange"],na.rm=TRUE),xlim=c(-3,3),ylim=c(0,1
 lines(density(temp_outputB$log2FoldChange,na.rm=TRUE),xlim=c(-3,3),col="black")
 lines(density(outputA$log2FoldChange,na.rm=TRUE),xlim=c(-3,3),col="red")
 lines(density(outputA[attribute_ids,"log2FoldChange"],na.rm=TRUE),xlim=c(-3,3),col="salmon")
 text(1.5,0.4,adj=c(0,0),labels="All - baseline",col="black")
 text(1.5,0.35,adj=c(0,0),labels="All - corrected",col="red")
 text(1.5,0.3,adj=c(0,0),labels=paste0(negCtrlName," - baseline"),col="grey")
 text(1.5,0.25,adj=c(0,0),labels=paste0(negCtrlName," - corrected"),col="salmon")
 abline(v=0)
 dev.off()
```

For which I get an error: 
`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'plot': need at least 2 points to select a bandwidth automatically`

If I comment this block out too, the entire pipeline runs fine.

**Comment by deweyhannah** [comment]
What are you using as your `negCtrlName` and `posCtrlName` in the inputs? Those are going to be specific to the project that you're running, the defaults are `negCtrl` and `expCtrl`. With the OL45 library there are a few different options. You can use `ctrl_neg` and `ctrl_pos` for the Tewhey Lab's standard set of negative and positive controls, or you can set the negative controls to `ctrl_neg-Yu-ORF` which was another set of negative controls that were being tested with this particular library. 

The lines that you have attempted to comment out are creating a new generalized column in the attributes file and setting everything to your overall project name except for the oligos that you are indicating are negative or positive controls, based on the `negCtrlName` and `posCtrlName` you are providing at the initial step. If you don't provide accurate names for these two variables it is not able to create the density plot when plotting for the negative controls, because they don't exist and you don't even have two points involved. 

Plotting the normalization curves gives you information about how the library is changing based on the summit shift or overall normalization. For instance if you are using `method='ssn'` in your submission of MPRAmodel, then you would be asking for a summit shift normalization based on the negative controls in your library. If you tried doing that with the incorrect `negCtrlName` then you would also be coming up on an error there. 

While it is tempting to assume that there may be some part of the code that is causing a specific problem it is important to look and see if all the information that you are passing to the function is in fact matching up. Your lab may choose to label the negative controls differently or the same as the Tewhey Lab does and the defaults are based on generalized options to help make clear what they represented.

**Comment by amysorekar** [comment]
Thank you. Setting the proper neg and pos ctrls fixed everything.
